------------------------------
--  CATEGORY table
------------------------------
CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    REGULAR_FEE VARCHAR2(255) NOT NULL,
    AVAILABILITY VARCHAR2(255) NOT NULL
);
------------------------------
--  TOOL table
------------------------------
CREATE TABLE TOOL (
    TOOL_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    BRAND_ID NUMBER,
    CONSTRAINT FK_TOOL_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID)
);
------------------------------
--  TOOL_SERIAL table
------------------------------
CREATE TABLE TOOL_SERIAL (
    SERIAL_ID NUMBER PRIMARY KEY,
    TOOL_ID NUMBER,
    SERIAL_NUMBER VARCHAR2(255),
    CATEGORY_ID NUMBER,
    STARTTIME TIMESTAMP,
    ENDTIME TIMESTAMP,
    CONSTRAINT FK_TOOL_SERIAL_TOOL FOREIGN KEY (TOOL_ID) REFERENCES TOOL(TOOL_ID),
    CONSTRAINT FK_TOOL_SERIAL_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);
------------------------------
--  TRUCK table
------------------------------
CREATE TABLE TRUCK (
    TRUCK_ID NUMBER PRIMARY KEY,
    TRUCK_NAME VARCHAR2(255),
    BRAND_ID NUMBER,
    CONSTRAINT FK_TRUCK_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID)
);
------------------------------
--  TRUCK_PLATE_NUMBER table
------------------------------
CREATE TABLE TRUCK_PLATE_NUMBER (
    PLATE_NUMBER_ID NUMBER PRIMARY KEY,
    TRUCK_ID NUMBER,
    LICENSE_PLATE_NUMBER VARCHAR2(255),
    CATEGORY_ID NUMBER,
    STARTTIME TIMESTAMP,
    ENDTIME TIMESTAMP,
    CONSTRAINT FK_TRUCK_PLATE_TRUCK FOREIGN KEY (TRUCK_ID) REFERENCES TRUCK(TRUCK_ID),
    CONSTRAINT FK_TRUCK_PLATE_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);
------------------------------
--  BRAND table
------------------------------
CREATE TABLE BRAND (
    BRAND_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    CONTACT VARCHAR2(255)
);
------------------------------
--  LATE_FEE table
------------------------------
CREATE TABLE LATE_FEE (
    PENALTY_ID NUMBER PRIMARY KEY,
    TOOL_LATE_FEE VARCHAR2(255),
    TRUCK_LATE_FEE VARCHAR2(255),
    RENTAL_ID NUMBER,
    CONSTRAINT FK_LATE_FEE_RENTAL FOREIGN KEY (RENTAL_ID) REFERENCES RENTAL(RENTAL_ID)
);
------------------------------
--  MEMBER table
------------------------------
CREATE TABLE MEMBER (
    MEMBER_ID NUMBER PRIMARY KEY,
    AGE NUMBER,
    FIRST_NAME VARCHAR2(255),
    LAST_NAME VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    POSTAL_CODE VARCHAR2(255),
    PHONE_NUMBER VARCHAR2(255)
);
------------------------------
-- RENTAL table
------------------------------
CREATE TABLE RENTAL (
    RENTAL_ID NUMBER PRIMARY KEY,
    RENT_DATE DATE,
    RETURN_DATE DATE DEFAULT NULL,
    MEMBER_ID NUMBER,
    TOOL_ID NUMBER,
    TRUCK_ID NUMBER,
    CONSTRAINT FK_RENTAL_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_RENTAL_TOOL FOREIGN KEY (TOOL_ID) REFERENCES TOOL(TOOL_ID),
    CONSTRAINT FK_RENTAL_TRUCK FOREIGN KEY (TRUCK_ID) REFERENCES TRUCK(TRUCK_ID)
);
------------------------------
-- TOOL_VIEW
------------------------------
CREATE OR REPLACE VIEW TOOL_VIEW AS
SELECT
    t.TOOL_ID,
    t.NAME AS TOOL_NAME,
    ts.SERIAL_NUMBER AS TOOL_SERIAL_NUMBER
FROM
    TOOL t
INNER JOIN TOOL_SERIAL ts ON t.TOOL_ID = ts.TOOL_ID
WHERE
    ts.ENDTIME IS NULL;
------------------------------
-- TRUCK_VIEW
------------------------------
CREATE OR REPLACE VIEW TRUCK_VIEW AS
SELECT
    tr.TRUCK_ID,
    tr.TRUCK_NAME,
    tpn.LICENSE_PLATE_NUMBER AS LICENSE_PLATE_NUMBER
FROM
    TRUCK tr
INNER JOIN TRUCK_PLATE_NUMBER tpn ON tr.TRUCK_ID = tpn.TRUCK_ID
WHERE
    tpn.ENDTIME IS NULL;
------------------------------
--  Tool History sequences
------------------------------
CREATE SEQUENCE  TOOL_HISTORY_SEQ  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 102 
NOCACHE  
NOORDER  
NOCYCLE  
NOKEEP  
NOSCALE  GLOBAL;
------------------------------
--  Tool sequences
------------------------------
CREATE SEQUENCE  TOOL_SEQ  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 105 
NOCACHE  
NOORDER  
NOCYCLE  
NOKEEP  
NOSCALE  GLOBAL;
------------------------------
--  Truck History sequences
------------------------------
CREATE SEQUENCE  TRUCK_HISTORY_SEQ  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 100 
NOCACHE  
NOORDER  
NOCYCLE  
NOKEEP  
NOSCALE  GLOBAL;
------------------------------
--  Truck sequences
------------------------------
CREATE SEQUENCE  TRUCK_SEQ  
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 102 
NOCACHE  
NOORDER  
NOCYCLE  
NOKEEP  
NOSCALE  GLOBAL;